#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-trilead-ssh2
Version  : 1.0.0.build217
Release  : 1
URL      : https://repo1.maven.org/maven2/com/trilead/trilead-ssh2/1.0.0-build217/trilead-ssh2-1.0.0-build217.jar
Source0  : https://repo1.maven.org/maven2/com/trilead/trilead-ssh2/1.0.0-build217/trilead-ssh2-1.0.0-build217.jar
Source1  : https://repo1.maven.org/maven2/com/trilead/trilead-ssh2/1.0.0-build217/trilead-ssh2-1.0.0-build217.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: mvn-trilead-ssh2-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-trilead-ssh2 package.
Group: Data

%description data
data components for the mvn-trilead-ssh2 package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/trilead/trilead-ssh2/1.0.0-build217
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/trilead/trilead-ssh2/1.0.0-build217

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/trilead/trilead-ssh2/1.0.0-build217
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/trilead/trilead-ssh2/1.0.0-build217


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/trilead/trilead-ssh2/1.0.0-build217/trilead-ssh2-1.0.0-build217.jar
/usr/share/java/.m2/repository/com/trilead/trilead-ssh2/1.0.0-build217/trilead-ssh2-1.0.0-build217.pom
